# Generated by Django 4.2.2 on 2023-06-07 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_api', '0002_apitest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('abbr', models.TextField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_score', models.IntegerField()),
                ('guest_score', models.IntegerField()),
                ('date', models.DateField(verbose_name='game date')),
                ('round_number', models.CharField(choices=[('QF', 'Quarter Final'), ('SF', 'Semi Final'), ('FI', 'Final'), ('WI', 'Winner')], default='QF', max_length=2, verbose_name='round type')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='league_api.team')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='league_api.team')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='league_api.team')),
            ],
        ),
    ]
